### ISSUE TITLE
Attachment control: deleting an in-progress file upload leaves the file in staging folder

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1507] opened 2020-02-24 04:04 UTC
**Describe the bug**
In a contribution wizard if you cancel an in progress upload, then upload the same file again. 
The second upload had a ‘(2)’ appended to the end of the filename. That implies that the original upload is still in the staging folder. 

**To Reproduce**

1. Start a contribution wizard with a file attachment control
2. While the file is uploading, click the bin icon to cancel the upload
3. Upload the same file
4. Notice the filename has a (2) at the end

**Expected behavior**
Cancelling a file upload, and uploading a file with the same name should result in the file having no (2) at the end

**Platform:**

- OpenEquella Version: 2020.1, 2019.2, 2018.2

**Additional context**
I'm pretty sure it never used to be like this, but the attachment control drag and drop functionality was rewritten in oEQ 6.5 (i think). It could be related to the fix that was done [here ](https://github.com/openequella/openEQUELLA/issues/316)

**Comment by cathfitz** [comment] 2020-02-25 23:23
Charlie has confirmed this happens with both standard attachment control and cloud control

**Comment by SammyIsConfused** [comment] 2021-09-07 01:06
No longer seems to be replicable on the head of develop - potentially worth closing.

**Comment by cathfitz** [comment] 2021-09-07 01:47
Can't reproduce

**Closed by cathfitz** 2021-09-07 01:47 UTC
