### ISSUE TITLE
Renovate bot currently failing

### ISSUE THREAD

**Issue by edalex-ian** [openequella/openEQUELLA#1468] opened 2020-02-06 01:55 UTC
Our renovate bot is currently failing to do updates - and has for some time:

![image](https://user-images.githubusercontent.com/43919233/73899135-c6e49f00-48df-11ea-985e-f0858b8ff54a.png)

The only WARN I'm seeing is (and I see no ERROR or FATAL):

```
WARN: Gradle run failed
{
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm -v \"/mnt/renovate/gh/openequella/openEQUELLA/import-export-tool\":\"/mnt/renovate/gh/openequella/openEQUELLA/import-export-tool\" -w \"/mnt/renovate/gh/openequella/openEQUELLA/import-export-tool\" renovate/gradle gradle --init-script renovate-plugin.gradle renovate",
    "stdout": "To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.6.4/userguide/gradle_daemon.html.\nDaemon will be stopped at the end of the build stopping after processing\nConfiguration on demand is an incubating feature.\n",
    "stderr": "\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nA problem occurred configuring root project 'import-export-tool'.\n> Failed to notify project evaluation listener.\n   > 'org.gradle.api.tasks.TaskInputs org.gradle.api.tasks.TaskInputs.file(java.lang.Object)'\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 28s\n",
    "message": "Command failed: docker run --rm -v \"/mnt/renovate/gh/openequella/openEQUELLA/import-export-tool\":\"/mnt/renovate/gh/openequella/openEQUELLA/import-export-tool\" -w \"/mnt/renovate/gh/openequella/openEQUELLA/import-export-tool\" renovate/gradle gradle --init-script renovate-plugin.gradle renovate\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nA problem occurred configuring root project 'import-export-tool'.\n> Failed to notify project evaluation listener.\n   > 'org.gradle.api.tasks.TaskInputs org.gradle.api.tasks.TaskInputs.file(java.lang.Object)'\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 28s\n",
    "stack": "Error: Command failed: docker run --rm -v \"/mnt/renovate/gh/openequella/openEQUELLA/import-export-tool\":\"/mnt/renovate/gh/openequella/openEQUELLA/import-export-tool\" -w \"/mnt/renovate/gh/openequella/openEQUELLA/import-export-tool\" renovate/gradle gradle --init-script renovate-plugin.gradle renovate\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nA problem occurred configuring root project 'import-export-tool'.\n> Failed to notify project evaluation listener.\n   > 'org.gradle.api.tasks.TaskInputs org.gradle.api.tasks.TaskInputs.file(java.lang.Object)'\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 28s\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
  },
  "cmd": "docker run --rm -v \"/mnt/renovate/gh/openequella/openEQUELLA/import-export-tool\":\"/mnt/renovate/gh/openequella/openEQUELLA/import-export-tool\" -w \"/mnt/renovate/gh/openequella/openEQUELLA/import-export-tool\" renovate/gradle gradle --init-script renovate-plugin.gradle renovate"
}
```

I note that @ChristianMurphy also had similar issues over in uPortal lands, and I see the CAS peeps also having issues: https://github.com/renovatebot/renovate/issues/4467

Do you have any thoughts @ChristianMurphy . I notice you're now using a self hosted setup. Is that just a uPortal thing, or a broader Apereo thing, or...?

**Comment by ChristianMurphy** [comment] 2020-02-06 17:51
Ideally I'd like to use renovate bot hosted.
When issues prevent it, I fallback to hosting it off my developer workstation.
Personally I'd rather have renovate self hosted, than not have renovate at all.

---

The local setup I have for uPortal is managed with a cron job that runs every 2 hours

```
0 */2 * * *  /home/developers/scripts/run-renovate.sh
```

and _run-renovate.sh_

```bash
#/bin/bash

renovate-github Jasig/uPortal-start --git-fs=https
```

and `renovate-github` is an alias for `renovate --token {github token goes here}`

---

> broader Apereo thing

I'd like it to be a broader Apereo thing, with Apereo footing the bill for paid renovate support for projects; both to prioritize fixing things Apereo projects need, and to support another open source project.
But this hasn't happened yet.

**Comment by edalex-ian** [comment] 2020-02-06 21:11
Great info there @ChristianMurphy , thanks for that. I think I'll read up on the renovate CLI then and see what I might be able to do.

Thanks.

**Comment by edalex-ian** [comment] 2020-02-16 22:09
See also: https://github.com/renovatebot/renovate/issues/5483

**Comment by edalex-ian** [comment] 2020-02-16 22:10
Interestingly, on the week-end renovate bot has kicked off again. Will monitor.

**Comment by ViceIce** [comment] 2020-02-20 05:59
@ChristianMurphy can you tell us at the mentioned renovate issue, what version or renovate you are using? We would like to find the root cause for this fail.

**Comment by ChristianMurphy** [comment] 2020-02-21 03:41
@viceice for which mentioned issue?
there are two renovatebot/renovate#5483 and renovatebot/renovate#4467

also note the work around I have is for uPortal-start (where I'm using renovate 19.100.0 to prevent a gradle mismatch between renovate and Gradle 4.3 which is used on that project)

I have not tested if that version works with openEquella.

**Comment by ChristianMurphy** [comment] 2020-03-10 03:54
renovate bot is up and running again, closing this issue out.

**Closed by ChristianMurphy** 2020-03-10 03:54 UTC
Labels: Tech debt
