### ISSUE TITLE
docker-compose database configuration issue

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#2474] opened 2020-10-30 17:26 UTC
**Describe the bug**
`docker-compose up -d` succeeds, but the logs are throwing an error with the postgre database connection (below).  Is there something missing from the documentation?

**To Reproduce**
Using docker-compose v 1.25.4 :
Run `docker-compose up -d`
Run `docker-compose logs` and note the errors with the database
I tried changing some of the configs in `defaults.xml`, `docker-compose.yml`, and 'Dockerfile`, removed the docker containers, and ran `docker-compose up -d --force-recreate --build`, but no joy.

**Expected behavior**
docker-compose should start up cleanly without external dependencies.  Configuration may be needed, but should be noted in documentation.

**Stacktrace**
```
database_1   | LOG:  database system is ready to accept connections
database_1   | FATAL:  password authentication failed for user "equellauser"
database_1   | DETAIL:  Role "equellauser" does not exist.
database_1   | 	Connection matched pg_hba.conf line 95: "host all all all md5"
```

**Platform:**

- OpenEquella Version: [2020.2.0-Alpha]
- OS: [Ubuntu 16]
- Docker-compose configuration: develop (20201020)

**Comment by edalex-ian** [comment] 2020-11-01 23:03
Heya @PenghaiZhang 

Could you please have a quick look at this for @cbeach47 ?

**Comment by PenghaiZhang** [comment] 2020-11-02 00:20
The issue is the database is not initialised. Previously, we just manually added a new database called `equella` and a user account. I will find a fix for this.

**Closed** 2021-04-12 05:31 UTC
Labels: Docker
