### ISSUE TITLE
Refactor LibAV usage to FFmpeg

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#3890] opened 2022-02-24 04:35 UTC
Rework oEQ to now depend on FFmpeg instead of LibAV

**Comment by edalex-ian** [comment] 2022-02-24 21:47
I see this is a duplicate of #697. So I'll close this one, and place the other (which has more info) in the 2022.2 milestone.

**Closed by edalex-ian** 2022-02-24 21:47 UTC
Labels: Edalex
